version: '3'

services:
  htd:
    restart: unless-stopped
    build: .
    environment:
      HTD_PUBLIC_PATH: "/htd/"
      HTD_DOCFILES_LINK_ROOT: "static/docfiles"
    env_file:
      - .env
    volumes:
      - "/srv/hostthedocs:/app/hostthedocs/static/docfiles"
      - ".:/app"
    labels:
      traefik.enable: true
      traefik.http.routers.htd.rule: PathPrefix(`/htd`)
      traefik.http.routers.htd.tls: false
      traefik.http.routers.htd.middlewares: htd
      traefik.http.routers.htd_secure.rule: PathPrefix(`/htd`)
      traefik.http.routers.htd_secure.tls: true
      traefik.http.routers.htd_secure.middlewares: strip-prefix
      traefik.http.services.htd.loadbalancer.server.port: 5000
      # strip-any prefix and ensure trailing slash for proper relative links
      # https://community.containo.us/t/middleware-to-add-the-if-needed/1895/13 
      traefik.http.middlewares.strip-prefix.chain.middlewares: strip-prefix-1,strip-prefix-2
      traefik.http.middlewares.strip-prefix-1.redirectregex.regex: ^(https?://[^/]+/[a-z0-9_]+)$$
      traefik.http.middlewares.strip-prefix-1.redirectregex.replacement: $${1}/
      traefik.http.middlewares.strip-prefix-1.redirectregex.permanent: true
      traefik.http.middlewares.strip-prefix-2.stripprefixregex.regex: /[a-z0-9_]+
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy

