version: '3'

services:
  htd:
    restart: unless-stopped
    build: .
    environment:
      HTD_PUBLIC_PATH: "/htd/"
      HTD_DOCFILES_LINK_ROOT: "static/docfiles"
    env_file:
      - .env
    volumes:
      - "/srv/hostthedocs:/app/hostthedocs/static/docfiles"
      - ".:/app"
    labels:
      traefik.enable: true
      traefik.http.routers.htd.rule: PathPrefix(`/htd`)
      traefik.http.routers.htd.tls: false
      traefik.http.routers.htd.middlewares: htd
      traefik.http.routers.htd_secure.rule: PathPrefix(`/htd`)
      traefik.http.routers.htd_secure.tls: true
      traefik.http.routers.htd_secure.middlewares: htd
      traefik.http.middlewares.htd.stripprefix.prefixes: /htd
      traefik.http.services.htd.loadbalancer.server.port: 5000
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy

